services:
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
      # - "5001:5001"
    depends_on:
      - database
    environment:
      connectionstrings__default_connection: "Server=database;Port=5432;Database=caes-guia;User Id=postgres;Password=admin;"
      TOKEN_KEY: "2441bdde-5984-4e0a-9c76-7aa6aa1f9736"

  app:
    build: ./web
    container_name: app
    depends_on:
      - api
    ports:
      - "3000:3000"
    command: "npm start"

  database:
    image: postgres
    container_name: database
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=caes-guia

volumes:
  db_volume:
