global using FluentAssertions;
global using Moq;
global using Xunit;
global using Domain.Entities;
global using Domain.Validators;
global using Service.Services;
global using Repository.Repositories;
global using App.Controllers;
global using FluentValidation;
