name: Update frontend docker registry

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./web/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/caes-guia-frontend:${{github.ref_name}}
