name: Update backend docker registry

on:
  push:
    tags:
      - '*'

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./api
      run: docker build . --file Dockerfile --tag caes-guia-backend:${{github.ref_name}}

    - uses: actions/checkout@v3
    - name: Push the docker image
      run: docker push caes-guia-backend:${{github.ref_name}}
