name: publish installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./installer
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -r ubuntu.16.10-x64
      working-directory: ./installer
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact
        path: /home/runner/work/caes-guia/caes-guia/installer/bin/Release/net7.0/ubuntu.16.10-x64/publish/
        
